// <auto-generated />
namespace EasyAccess.Repository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Onebin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Onebin));
        
        string IMigrationMetadata.Id
        {
            get { return "201310170807531_Onebin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
