// <auto-generated />
namespace Demo.Repository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddModuleForm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddModuleForm));
        
        string IMigrationMetadata.Id
        {
            get { return "201312120959586_AddModuleForm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
